<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <IsPackable>false</IsPackable>
        <UserSecretsId>Sarti2004.PianoFolder-PluginDevelopment</UserSecretsId>
    </PropertyGroup>


    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>

        <PackageReference Include="MacroDeck.Plugin.Analyzers" PrivateAssets="all" />
        <PackageReference Include="MacroDeck.Localization" />
        <PackageReference Include="MacroDeck.Plugin.Hosting" />
        <PackageReference Include="MacroDeck.Plugin.Serilog" />
        <PackageReference Include="MacroDeck.Sdk" />
        <PackageReference Include="MacroDeck.Ui" />
        <PackageReference Include="MacroDeck.Ui.Model" />
    </ItemGroup>


    <ItemGroup>
        <Content Include="manifest.json" CopyToOutputDirectory="PreserveNewest" />
        <Content Include="Assets\icon.svg" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

</Project>
